import React, { useEffect, useMemo, useState } from "react";
import { Archive, Bell, BellOff, Check, ClipboardCheck, Copy, Edit3, FileText, MessageCircle, Paperclip, Pin, Plus, Reply, Search, Send, Smile, Trash2, UserCheck, UserRound, X } from "lucide-react";
import { db, ORG, checked, date, digits } from "./lib";
import { useT, label } from "./i18n";
import { emailSubject, missingPlaceholders, renderTemplate, sendFormSubmitEmail, valuesForPatient } from "./communicationTemplates";
import { SmartTextControl, currentSuggestions } from "./autocomplete";
import ContextActions from "./ContextActions";
import { PatientPicker, TemplatePicker } from "./PatientPicker";

const nameOf = (row) => row?.preferred_name || row?.full_name || row?.name || row?.email || "—";
const preview = (value, max = 180) => String(value || "").trim().slice(0, max);
const reactions = ["👍", "❤️", "😂", "👏", "❓", "✅"];
const communicationCategories = [
  ["agendamento", "Agendamento"],
  ["lembrete", "Lembretes"],
  ["pos_procedimento", "Pós-procedimento"],
  ["orientacao", "Orientações"],
  ["financeiro", "Financeiro"],
  ["documentos", "Documentos"],
  ["feedback", "Feedback"],
  ["marketing", "Marketing"],
  ["administrativo", "Administrativo"],
];
const wa = (phone, body) => `https://web.whatsapp.com/send?phone=${encodeURIComponent(digits(phone))}&text=${encodeURIComponent(body)}`;
const cn = (value = "") => `button ${value}`.trim();

function Button({ icon: Icon, className = "", children, ...props }) { return <button className={cn(className)} {...props}>{Icon && <Icon size={17} aria-hidden="true" />}{children}</button>; }
function Field({ title, value, onChange, options, placeholder = "", required = false }) { if (options && /paciente|patient/i.test(String(title || ""))) return <PatientPicker title={title} value={value} onChange={onChange} initial={options.find((option) => option.value === value) ? { id: value, full_name: options.find((option) => option.value === value)?.label } : null} />; return <label className="field"><span>{title}</span>{options ? <select value={value || ""} onChange={(e) => onChange(e.target.value)} required={required}>{options.map((option) => <option value={option.value} key={option.value}>{option.label}</option>)}</select> : <SmartTextControl value={value || ""} onChange={onChange} suggestions={currentSuggestions()} placeholder={placeholder} required={required} />}</label>; }
function Dialog({ title, close, children }) { return <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><Button className="icon" icon={X} onClick={close} aria-label="Close" /></header>{children}</section></div>; }

function ExternalMessage({ patients, initialPatient, member, close, notify, refresh }) {
  const t = useT();
  const [patientId, setPatientId] = useState(initialPatient?.id || "");
  const [channel, setChannel] = useState("whatsapp");
  const [category, setCategory] = useState("agendamento");
  const [body, setBody] = useState("");
  const [subject, setSubject] = useState("");
  const [templates, setTemplates] = useState([]);
  const [templateId, setTemplateId] = useState("");
  const [busy, setBusy] = useState(false);
  const patient = patients.find((row) => row.id === patientId);
  const recipient = channel === "email" ? patient?.email : patient?.phone;
  const values = valuesForPatient(patient, member);
  const missing = missingPlaceholders(body, values);
  useEffect(() => { checked(db.from("communication_templates").select("*").eq("active", true).order("category,name,variant")).then(setTemplates).catch(() => setTemplates([])); }, []);
  useEffect(() => { if (templateId === "__free__") return; const item = templates.find((row) => row.id === templateId) || templates.find((row) => row.channel === channel && row.category === category) || templates.find((row) => row.channel === channel); if (item) { setTemplateId(item.id); setCategory(item.category || category); setSubject(renderTemplate(item.subject, values)); setBody(renderTemplate(item.body, values)); } }, [templates, channel, category, patientId, templateId]);
  const selected = templates.find((row) => row.id === templateId);
  const saveTemplate = async (asNew = false) => {
    if (!selected || !body.trim()) return;
    const name = asNew ? window.prompt(t("Nome do novo modelo", "Name for the new template"), selected.name) : selected.name;
    if (!name?.trim()) return;
    try {
      const payload = { name: name.trim(), category, channel, variant: selected.variant || "standard", subject, body: body.trim(), sender_mode: selected.sender_mode || "sender", sensitive: Boolean(selected.sensitive), created_by: member.user_id };
      if (asNew) await checked(db.from("communication_templates").insert({ organization_id: ORG, ...payload }));
      else await checked(db.from("communication_templates").update(payload).eq("id", selected.id));
      const rows = await checked(db.from("communication_templates").select("*").eq("active", true).order("category,name,variant")); setTemplates(rows); notify(t(asNew ? "Modelo salvo para uso futuro." : "Modelo atual substituído.", asNew ? "Template saved for future use." : "Current template updated."));
    } catch { notify(t("Não foi possível salvar o modelo.", "Could not save the template.")); }
  };
  const renameTemplate = async () => {
    if (!selected) return;
    const name = window.prompt(t("Novo nome do modelo", "New template name"), selected.name);
    if (!name?.trim() || name.trim() === selected.name) return;
    try { await checked(db.from("communication_templates").update({ name: name.trim() }).eq("id", selected.id)); setTemplates((rows) => rows.map((row) => row.id === selected.id ? { ...row, name: name.trim() } : row)); notify(t("Modelo renomeado.", "Template renamed.")); } catch { notify(t("Não foi possível renomear o modelo.", "Could not rename the template.")); }
  };
  const submit = async (event) => {
    event.preventDefault();
    if (!patient || !recipient || !body.trim() || missing.length) return notify(t("Preencha destinatário e mensagem.", "Complete recipient and message."));
    const finalSubject = channel === "email" ? emailSubject(subject, selected?.name) : subject;
    const target = channel === "whatsapp" ? wa(recipient, body) : null;
    const popup = target ? window.open(target, "_blank", "noopener,noreferrer") : null;
    setBusy(true);
    try {
      if (channel === "email") await sendFormSubmitEmail({ recipient, subject: finalSubject, body, patient, sender: member.email || member.name });
      const row = await checked(db.from("communications").insert({ organization_id: ORG, patient_id: patient.id, channel, direction: "outbound", visibility: "external", category, subject: finalSubject, body: body.trim(), rendered_signature: "", recipient_name: nameOf(patient), recipient_address: recipient, status: "rascunho", packet_sha256: "", created_by: member.user_id }).select().single());
      await checked(db.from("communications").update({ status: "nao_confirmado", sent_at: channel === "email" ? new Date().toISOString() : null }).eq("id", row.id));
      if (!popup) notify(t("A nova aba foi bloqueada.", "The new tab was blocked."));
      refresh(); close();
    } catch { popup?.close(); notify(t("Não foi possível registrar a comunicação.", "Could not record communication.")); }
    finally { setBusy(false); }
  };
  return <Dialog title={t("Mensagem para paciente", "Patient message")} close={close}><form className="form-grid" onSubmit={submit}><PatientPicker value={patientId} onChange={setPatientId} initial={patients.find((row) => row.id === patientId)} /><Field title={t("Canal", "Channel")} value={channel} onChange={(value) => { setChannel(value); setTemplateId(""); }} options={[{ value: "whatsapp", label: "WhatsApp Web" }, { value: "email", label: "Email" }]} /><Field title={t("Categoria da mensagem", "Message category")} value={category} onChange={(value) => { setCategory(value); setTemplateId(""); }} options={communicationCategories.map(([value, labelText]) => ({ value, label: t(labelText, labelText) }))} /><TemplatePicker title={t("Modelo", "Template")} templates={[{ id: "__free__", name: t("Mensagem livre", "Free message"), body: "", channel, category } , ...templates.filter((row) => row.channel === channel)]} channel={channel} value={templateId} onChange={(value) => { setTemplateId(value); const row = templates.find((item) => item.id === value); if (row?.category) setCategory(row.category); if (value === "__free__") { setBody(""); setSubject(""); } }} />{channel === "email" && <Field title={t("Assunto", "Subject")} value={subject} onChange={setSubject} required />}<label className="field wide"><span>{t("Mensagem", "Message")}</span><textarea value={body} onChange={(e) => setBody(e.target.value)} rows="8" required />{missing.length > 0 && <small className="notice error">{missing.join(", ")}</small>}</label><footer className="form-footer"><Button type="button" onClick={() => saveTemplate(false)} icon={Send} disabled={!selected}>{t("Salvar modelo atual", "Save current template")}</Button><Button type="button" onClick={() => saveTemplate(true)} icon={Copy}>{t("Salvar como novo", "Save as new")}</Button><Button type="button" onClick={renameTemplate} icon={Edit3} disabled={!selected}>{t("Renomear", "Rename")}</Button><Button type="button" onClick={close}>{t("Cancelar", "Cancel")}</Button><Button className="primary" icon={Send} disabled={busy}>{t(channel === "email" ? "Enviar email" : "Abrir canal", channel === "email" ? "Send email" : "Open channel")}</Button></footer></form></Dialog>;
}

function MessageCard({ row, messages, member, staff, onReply, onEdit, onDelete, onReact, onCopy, onTask, onFile, t }) {
  const sender = staff.find((item) => item.user_id === row.sender_id);
  const actions = row.deleted_at ? [] : [
    { icon: Reply, label: t("Responder", "Reply"), onClick: () => onReply(row) },
    { icon: Copy, label: t("Copiar mensagem", "Copy message"), onClick: () => onCopy(row.body) },
    { icon: ClipboardCheck, label: t("Criar tarefa", "Create task"), onClick: () => onTask(row) },
    row.sender_id === member.user_id && { icon: Edit3, label: t("Editar mensagem", "Edit message"), onClick: () => onEdit(row) },
    (row.sender_id === member.user_id || ["proprietario", "suporte_ti"].includes(member.role)) && { icon: Trash2, label: t("Excluir mensagem", "Delete message"), danger: true, onClick: () => onDelete(row) },
  ];
  return <ContextActions label={t("Mensagem", "Message")} actions={actions} className="message-context-actions">
  <article className={`${row.sender_id === member.user_id ? "own" : ""} ${row.deleted_at ? "deleted" : ""}`}>
    <div className="message-meta"><strong>{row.sender_id === member.user_id ? t("Você", "You") : nameOf(sender)}</strong><small>{date(row.created_at, true)}{row.edited_at && ` · ${t("editada", "edited")}`}</small></div>
    {row.reply_to_id && <div className="message-reply">↳ {preview(messages.find((item) => item.id === row.reply_to_id)?.body, 100)}</div>}
    <p className="preserve">{row.deleted_at ? t("Mensagem excluída", "Message deleted") : row.body}</p>
    {row.attachments?.map((file) => <button type="button" className="message-attachment" key={file.id} onClick={() => onFile(file)}><FileText size={15} /> {file.original_name}</button>)}
    {!row.deleted_at && <><div className="message-reactions">{reactions.map((emoji) => { const count = row.reactions?.filter((item) => item.emoji === emoji).length || 0; const active = row.reactions?.some((item) => item.user_id === member.user_id && item.emoji === emoji); return <button type="button" className={active ? "active" : ""} key={emoji} onClick={() => onReact(row, emoji)}>{emoji}{count ? ` ${count}` : ""}</button>; })}</div><div className="message-actions"><Button className="icon" icon={Reply} onClick={() => onReply(row)} aria-label={t("Responder", "Reply")} /><Button className="icon" icon={Copy} onClick={() => onCopy(row.body)} aria-label={t("Copiar", "Copy")} /><Button className="icon" icon={ClipboardCheck} onClick={() => onTask(row)} aria-label={t("Criar tarefa", "Create task")} />{row.sender_id === member.user_id && <Button className="icon" icon={Edit3} onClick={() => onEdit(row)} aria-label={t("Editar", "Edit")} />}{(row.sender_id === member.user_id || ["proprietario", "suporte_ti"].includes(member.role)) && <Button className="icon danger" icon={Trash2} onClick={() => onDelete(row)} aria-label={t("Excluir", "Delete")} />}</div></>}
  </article>
  </ContextActions>;
}

export default function CommunicationHub({ member, openPatient, version, writable, notify }) {
  const t = useT();
  const [data, setData] = useState({ conversations: [], patients: [], staff: [], communications: [], reads: [], notifications: [] });
  const [selected, setSelected] = useState(null), [messages, setMessages] = useState([]), [text, setText] = useState(""), [search, setSearch] = useState(""), [filter, setFilter] = useState("all"), [title, setTitle] = useState(""), [direct, setDirect] = useState(""), [patientContext, setPatientContext] = useState(""), [replyTo, setReplyTo] = useState(null), [editing, setEditing] = useState(null), [external, setExternal] = useState(null), [noticeOpen, setNoticeOpen] = useState(false), [sending, setSending] = useState(false);
  const loadMessages = async (id) => { if (!id) return; const rows = await checked(db.from("communication_messages").select("*").eq("conversation_id", id).order("created_at").range(0, 299)).catch(() => []); const ids = rows.map((row) => row.id); const [reacts, files] = await Promise.all([ids.length ? checked(db.from("communication_reactions").select("*").in("message_id", ids)).catch(() => []) : [], ids.length ? checked(db.from("communication_attachments").select("*").in("message_id", ids)).catch(() => []) : []]); setMessages(rows.map((row) => ({ ...row, reactions: reacts.filter((item) => item.message_id === row.id), attachments: files.filter((item) => item.message_id === row.id) }))); };
  const load = async () => { try { const [conversations, patients, staff, communications, reads, notifications] = await Promise.all([
    checked(db.from("communication_conversations").select("id,organization_id,title,kind,patient_id,created_by,created_at,updated_at,archived_at,pinned_at,last_message_at,last_message_preview,patients(id,full_name,preferred_name)").order("pinned_at", { ascending: false, nullsFirst: false }).order("updated_at", { ascending: false }).limit(200)),
    checked(db.from("patients").select("id,full_name,preferred_name,phone,email,status").eq("status", "ativo").order("full_name").limit(500)), checked(db.from("memberships").select("user_id,name,email,role").eq("status", "ativo").order("name")), checked(db.from("communications").select("*,patients(id,full_name,preferred_name)").order("created_at", { ascending: false }).limit(120)), checked(db.from("communication_reads").select("*").eq("user_id", member.user_id)), checked(db.from("communication_notifications").select("*").eq("user_id", member.user_id).is("read_at", null).order("created_at", { ascending: false }).limit(50)),
  ]); setData({ conversations, patients, staff, communications, reads, notifications }); setSelected((current) => current && conversations.some((row) => row.id === current.id) ? current : conversations.find((row) => !row.archived_at) || conversations[0] || null); } catch { notify(t("Não foi possível carregar a comunicação.", "Could not load communication.")); } };
  useEffect(() => { load(); }, [version, member.user_id]);
  useEffect(() => { loadMessages(selected?.id); if (!selected?.id) return; const now = new Date().toISOString(); checked(db.from("communication_reads").upsert({ organization_id: ORG, conversation_id: selected.id, user_id: member.user_id, last_read_at: now }, { onConflict: "organization_id,conversation_id,user_id" })).then(() => setData((current) => ({ ...current, reads: [...current.reads.filter((row) => row.conversation_id !== selected.id), { conversation_id: selected.id, user_id: member.user_id, last_read_at: now }] }))).catch(() => null); }, [selected?.id]);
  useEffect(() => { if (!selected?.id) return; setText(localStorage.getItem(`communication-draft:${selected.id}`) || ""); }, [selected?.id]);
  useEffect(() => { if (selected?.id) localStorage.setItem(`communication-draft:${selected.id}`, text); }, [selected?.id, text]);
  useEffect(() => { const channel = db.channel(`communication-${member.user_id}`).on("postgres_changes", { event: "*", schema: "public", table: "communication_messages", filter: `organization_id=eq.${ORG}` }, (payload) => { if (payload.eventType === "INSERT" && payload.new?.sender_id !== member.user_id && typeof Notification !== "undefined" && Notification.permission === "granted" && !readFor(payload.new.conversation_id)?.muted_until) new Notification(t("Nova mensagem interna", "New internal message"), { body: preview(payload.new.body) }); load(); if (selected?.id) loadMessages(selected.id); }).on("postgres_changes", { event: "*", schema: "public", table: "communication_notifications", filter: `user_id=eq.${member.user_id}` }, load).subscribe(); return () => { db.removeChannel(channel); }; }, [member.user_id, selected?.id]);
  const readFor = (id) => data.reads.find((row) => row.conversation_id === id);
  const isUnread = (row) => row.last_message_at && (!readFor(row.id)?.last_read_at || new Date(row.last_message_at) > new Date(readFor(row.id).last_read_at));
  const conversations = useMemo(() => data.conversations.filter((row) => filter === "archived" ? row.archived_at : !row.archived_at).filter((row) => filter !== "unread" || isUnread(row)).filter((row) => !search || `${row.title} ${row.last_message_preview} ${nameOf(row.patients)}`.toLowerCase().includes(search.toLowerCase())), [data, filter, search]);
  const createTeam = async () => { try { const row = await checked(db.from("communication_conversations").insert({ organization_id: ORG, title: title.trim() || "Equipe", kind: "equipe", patient_id: patientContext || null, created_by: member.user_id }).select("*,patients(id,full_name,preferred_name)").single()); setTitle(""); setPatientContext(""); setSelected(row); await load(); } catch { notify(t("Não foi possível criar o chat.", "Could not create chat.")); } };
  const createDirect = async () => { if (!direct) return; try { const person = data.staff.find((row) => row.user_id === direct); const row = await checked(db.from("communication_conversations").insert({ organization_id: ORG, title: nameOf(person), kind: "direta", created_by: member.user_id }).select("*,patients(id,full_name,preferred_name)").single()); await checked(db.from("communication_participants").insert([{ organization_id: ORG, conversation_id: row.id, user_id: member.user_id }, { organization_id: ORG, conversation_id: row.id, user_id: direct }])); setDirect(""); setSelected(row); await load(); } catch { notify(t("Não foi possível iniciar a conversa.", "Could not start conversation.")); } };
  const send = async (event) => { event.preventDefault(); if (!selected || !text.trim() || sending) return; setSending(true); try { await checked(db.from("communication_messages").insert({ organization_id: ORG, conversation_id: selected.id, sender_id: member.user_id, body: text.trim(), reply_to_id: replyTo?.id || null, client_message_id: crypto.randomUUID(), message_type: "text", metadata: {} })); setText(""); setReplyTo(null); await loadMessages(selected.id); } catch { notify(t("Não foi possível enviar a mensagem.", "Could not send message.")); } finally { setSending(false); } };
  const updateMessage = async () => { if (!editing?.body.trim()) return; try { await checked(db.from("communication_messages").update({ body: editing.body.trim() }).eq("id", editing.id)); setEditing(null); await loadMessages(selected.id); } catch { notify(t("Não foi possível editar.", "Could not edit.")); } };
  const deleteMessage = async (row) => { if (!window.confirm(t("Excluir esta mensagem?", "Delete this message?"))) return; try { await checked(db.from("communication_messages").update({ deleted_at: new Date().toISOString() }).eq("id", row.id)); await loadMessages(selected.id); } catch { notify(t("Não foi possível excluir.", "Could not delete.")); } };
  const react = async (row, emoji) => { const mine = row.reactions?.some((item) => item.user_id === member.user_id && item.emoji === emoji); try { if (mine) await checked(db.from("communication_reactions").delete().eq("message_id", row.id).eq("user_id", member.user_id).eq("emoji", emoji)); else await checked(db.from("communication_reactions").insert({ organization_id: ORG, message_id: row.id, user_id: member.user_id, emoji })); await loadMessages(selected.id); } catch { notify(t("Não foi possível reagir.", "Could not react.")); } };
  const attach = async (event) => { const files = [...event.target.files].slice(0, 5); event.target.value = ""; if (!files.length || !selected) return; if (files.some((file) => file.size > 10485760)) return notify(t("Cada arquivo deve ter no máximo 10 MB.", "Each file must be 10 MB or smaller.")); try { const row = await checked(db.from("communication_messages").insert({ organization_id: ORG, conversation_id: selected.id, sender_id: member.user_id, body: files.map((file) => file.name).join(", "), message_type: "file", client_message_id: crypto.randomUUID(), metadata: {} }).select().single()); for (const file of files) { const path = `${ORG}/${selected.id}/${row.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; await checked(db.storage.from("communication-private").upload(path, file, { upsert: false, contentType: file.type || "application/octet-stream" })); await checked(db.from("communication_attachments").insert({ organization_id: ORG, message_id: row.id, storage_path: path, original_name: file.name, mime_type: file.type || "application/octet-stream", size_bytes: file.size, created_by: member.user_id })); } await loadMessages(selected.id); } catch { notify(t("Não foi possível anexar o arquivo.", "Could not attach file.")); } };
  const updateConversation = async (field) => { if (!selected) return; try { await checked(db.from("communication_conversations").update({ [field]: selected[field] ? null : new Date().toISOString() }).eq("id", selected.id)); await load(); } catch { notify(t("Não foi possível atualizar a conversa.", "Could not update conversation.")); } };
  const deleteConversation = async () => { if (!selected || !window.confirm(t("Excluir esta conversa e todas as mensagens? Esta ação não pode ser desfeita.", "Delete this conversation and all messages? This cannot be undone."))) return; try { const deletedId = selected.id; await checked(db.from("communication_conversations").delete().eq("id", deletedId)); localStorage.removeItem(`communication-draft:${deletedId}`); setSelected(null); setMessages([]); await load(); notify(t("Conversa excluída.", "Conversation deleted.")); } catch { notify(t("Não foi possível excluir a conversa. Verifique sua permissão.", "Could not delete the conversation. Check your permission.")); } };
  const mute = async () => { const read = readFor(selected.id); await checked(db.from("communication_reads").upsert({ organization_id: ORG, conversation_id: selected.id, user_id: member.user_id, last_read_at: read?.last_read_at || new Date().toISOString(), muted_until: read?.muted_until ? null : "9999-12-31T00:00:00Z" }, { onConflict: "organization_id,conversation_id,user_id" })).then(load).catch(() => notify(t("Não foi possível silenciar.", "Could not mute."))); };
  const task = async (row) => { try { await checked(db.from("tasks").insert({ organization_id: ORG, patient_id: selected.patient_id || null, title: preview(row.body, 160), due_at: new Date().toISOString(), priority: "normal", status: "pendente", created_by: member.user_id, category: "operacional", source_type: "manual" })); notify(t("Tarefa criada.", "Task created.")); } catch { notify(t("Não foi possível criar a tarefa.", "Could not create task.")); } };
  const file = async (attachment) => { const result = await db.storage.from("communication-private").createSignedUrl(attachment.storage_path, 300); if (result.data?.signedUrl) window.open(result.data.signedUrl, "_blank", "noopener,noreferrer"); };
  const copy = async (body) => { await navigator.clipboard?.writeText(body); notify(t("Mensagem copiada.", "Message copied.")); };
  const markAll = async () => { await checked(db.from("communication_notifications").update({ read_at: new Date().toISOString() }).eq("user_id", member.user_id).is("read_at", null)).catch(() => null); setData((current) => ({ ...current, notifications: [] })); };
  return <>
    <div className="communication-hub">
      <section className="communication-column internal-chat-column">
        <header className="communication-column-head"><div><p className="eyebrow">{t("Somente equipe", "Team only")}</p><h2>{t("Comunicação interna", "Internal communication")}</h2><p className="subtle">{t("Converse, compartilhe contexto e transforme mensagens em ações.", "Chat, share context, and turn messages into actions.")}</p></div><div className="communication-header-actions"><Button className="icon" icon={Bell} onClick={() => typeof Notification !== "undefined" && Notification.requestPermission()} aria-label={t("Ativar notificações", "Enable notifications")} /><Button className="icon" icon={BellOff} onClick={() => setNoticeOpen((value) => !value)} aria-label={t("Notificações", "Notifications")} />{data.notifications.length > 0 && <span className="notification-badge">{data.notifications.length}</span>}</div></header>
        {noticeOpen && <div className="communication-notifications"><strong>{t("Notificações não lidas", "Unread notifications")}</strong>{data.notifications.slice(0, 8).map((item) => <button type="button" key={item.id} onClick={() => { const row = data.conversations.find((conversation) => conversation.id === item.conversation_id); if (row) setSelected(row); setNoticeOpen(false); }}><b>{item.title}</b><span>{item.body}</span></button>)}<Button onClick={markAll}>{t("Marcar todas como lidas", "Mark all as read")}</Button></div>}
        <div className="communication-create"><Field title={t("Novo chat da equipe", "New team chat")} value={title} onChange={setTitle} placeholder={t("Ex.: Operação", "E.g. Operations")} /><Button icon={Plus} className="primary" onClick={createTeam} disabled={!writable}>{t("Criar", "Create")}</Button><Field title={t("Contexto opcional", "Optional context")} value={patientContext} onChange={setPatientContext} options={[{ value: "", label: t("Nenhum paciente", "No patient") }, ...data.patients.map((row) => ({ value: row.id, label: nameOf(row) }))]} /><Field title={t("Falar com profissional", "Talk to professional")} value={direct} onChange={setDirect} options={[{ value: "", label: t("Selecionar membro", "Select member") }, ...data.staff.filter((row) => row.user_id !== member.user_id).map((row) => ({ value: row.user_id, label: `${nameOf(row)} · ${label(row.role, t)}` }))]} /><Button icon={UserCheck} onClick={createDirect} disabled={!writable || !direct}>{t("Iniciar", "Start")}</Button></div>
        <div className="team-chat-toolbar"><label className="search"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={t("Buscar conversas…", "Search conversations…")} /></label><div className="segmented"><button className={filter === "all" ? "selected" : ""} onClick={() => setFilter("all")}>{t("Todas", "All")}</button><button className={filter === "unread" ? "selected" : ""} onClick={() => setFilter("unread")}>{t("Não lidas", "Unread")}</button><button className={filter === "archived" ? "selected" : ""} onClick={() => setFilter("archived")}>{t("Arquivadas", "Archived")}</button></div></div>
        <div className="team-chat-layout"><nav className="team-chat-list">{conversations.map((row) => <button type="button" key={row.id} className={selected?.id === row.id ? "selected" : ""} onClick={() => setSelected(row)}><div className="conversation-title"><strong>{row.pinned_at && <Pin size={13} />} {row.title || t("Equipe", "Team")}</strong>{isUnread(row) && <span className="unread-dot" />}</div><small>{row.patients ? `${t("Paciente", "Patient")}: ${nameOf(row.patients)}` : row.kind === "direta" ? t("Conversa direta", "Direct conversation") : t("Equipe", "Team")}</small><span className="conversation-preview">{row.last_message_preview || t("Nenhuma mensagem", "No messages")}</span></button>)}{!conversations.length && <p className="subtle">{t("Nenhuma conversa encontrada.", "No conversations found.")}</p>}</nav>
            <div className="team-chat-thread">{selected ? <><header className="team-chat-thread-head"><div><strong>{selected.title || t("Equipe", "Team")}</strong>{selected.patients && <button type="button" className="context-link" onClick={() => openPatient(selected.patients)}><UserRound size={14} /> {nameOf(selected.patients)}</button>}</div><div className="thread-actions"><Button className="icon" icon={Pin} onClick={() => updateConversation("pinned_at")} aria-label={t("Fixar", "Pin")} /><Button className="icon" icon={readFor(selected.id)?.muted_until ? Bell : BellOff} onClick={mute} aria-label={t("Silenciar", "Mute")} /><Button className="icon" icon={Archive} onClick={() => updateConversation("archived_at")} aria-label={t("Arquivar", "Archive")} />{writable && <Button className="icon danger" icon={Trash2} onClick={deleteConversation} aria-label={t("Excluir conversa", "Delete conversation")} />}</div></header>
            <div className="team-chat-messages" aria-live="polite">{messages.map((row) => <MessageCard key={row.id} row={row} messages={messages} member={member} staff={data.staff} onReply={setReplyTo} onEdit={(item) => setEditing({ id: item.id, body: item.body })} onDelete={deleteMessage} onReact={react} onCopy={copy} onTask={task} onFile={file} t={t} />)}{!messages.length && <p className="subtle">{t("Nenhuma mensagem ainda.", "No messages yet.")}</p>}</div>
            {writable && <form className="team-chat-compose" onSubmit={send}>{replyTo && <div className="reply-banner">{t("Respondendo a", "Replying to")} {preview(replyTo.body, 90)} <Button className="icon" icon={X} type="button" onClick={() => setReplyTo(null)} /></div>}{editing && <div className="reply-banner"><span>{t("Editando mensagem", "Editing message")}</span><Button type="button" className="primary" onClick={updateMessage}>{t("Salvar", "Save")}</Button><Button className="icon" icon={X} type="button" onClick={() => setEditing(null)} /></div>}<textarea value={editing ? editing.body : text} onChange={(event) => editing ? setEditing({ ...editing, body: event.target.value }) : setText(event.target.value)} placeholder={t("Escreva para a equipe… Use os botões para mencionar.", "Write to the team… Use the buttons to mention.")} required /><div className="compose-tools"><label className="button" title={t("Anexar arquivo", "Attach file")}><Paperclip size={17} /><input type="file" hidden multiple accept="image/*,application/pdf,text/plain,audio/webm,audio/ogg" onChange={attach} /></label><div className="mention-menu">{data.staff.filter((row) => row.user_id !== member.user_id).slice(0, 8).map((row) => <button type="button" key={row.user_id} onClick={() => setText((value) => `${value}${value ? " " : ""}@${nameOf(row)} `)}>@{nameOf(row)}</button>)}</div><Button type="button" icon={Smile} onClick={() => setText((value) => `${value}${value ? " " : ""}🙂`)} aria-label={t("Inserir emoji", "Insert emoji")} /><Button className="primary" icon={Send} disabled={sending}>{t("Enviar", "Send")}</Button></div></form>}
          </> : <p className="subtle">{t("Selecione ou crie um chat interno.", "Select or create an internal chat.")}</p>}</div>
        </div>
      </section>
      <section className="communication-column"><header className="communication-column-head"><div><p className="eyebrow">{t("Pacientes e clientes", "Patients and clients")}</p><h2>{t("Comunicação externa", "External communication")}</h2></div><Button icon={MessageCircle} className="primary" onClick={() => setExternal({})} disabled={!writable}>{t("Nova mensagem", "New message")}</Button></header><div className="communication-list">{data.communications.map((row) => <article className="communication-card" key={row.id}><span className="communication-card-icon"><MessageCircle size={17} /></span><div><strong>{nameOf(row.patients) || row.recipient_name}</strong><small>{row.channel} · {label(row.status, t)} · {date(row.created_at, true)}</small><p className="preserve communication-preview">{row.body}</p></div>{row.patients && <Button icon={UserRound} onClick={() => openPatient(row.patients)}>{t("Paciente", "Patient")}</Button>}</article>)}</div></section>
    </div>{external && <ExternalMessage patients={data.patients} initialPatient={external.patient} member={member} close={() => setExternal(null)} notify={notify} refresh={load} />}<div className="sr-only" aria-live="polite">{data.notifications.length ? `${data.notifications.length} ${t("notificações", "notifications")}` : ""}</div>
  </>;
}
