begin;
alter table public.procedures add column if not exists official_information jsonb not null default '{}' check(jsonb_typeof(official_information)='object');
alter table public.procedure_versions alter column created_by drop not null;

update public.procedures p set official_information = case
  when p.name ilike 'Laser CO₂%' then jsonb_build_object('authority','FDA 510(k) summary / Lumenis AcuPulse','official_fact','The AcuPulse CO₂ system is indicated for dermatology and plastic surgery applications including laser skin resurfacing, laser dermabrasion and treatment of wrinkles/texture irregularities, acne scars and selected pigmentation-related conditions, subject to the exact model, accessories and labeling.','operational_limit','The FDA clearance is not a patient-specific prescription and does not define Franciele’s settings, eligibility or local professional scope.','source','https://www.accessdata.fda.gov/cdrh_docs/pdf21/K212703.pdf')
  when p.name ilike 'Laser Harmony%' then jsonb_build_object('authority','Alma Laser official Harmony XL PRO information','official_fact','Harmony XL PRO is a multi-application platform whose official indications include skin rejuvenation/tone/texture, vascular lesions, skin remodeling/tightening, pigmented lesions and tattoos, hair removal, acne and acne scars; the applicable indication depends on the installed applicator and labeling.','operational_limit','Do not infer a diagnosis or select an applicator from the platform name alone. Confirm the installed model, registration, IFU and professional assessment.','source','https://almalasers.com/product/harmony-xl-pro/')
  when p.name ilike 'Laser LightSheer%' then jsonb_build_object('authority','Lumenis official LightSheer DUET information','official_fact','LightSheer DUET is an 800 nm diode-laser platform with two handpieces for hair removal; the manufacturer describes hair reduction and cites clearance for hair removal/permanent hair reduction and pseudofolliculitis barbae, with additional indications depending on the exact system and labeling.','operational_limit','Wavelength and manufacturer claims do not replace skin assessment, contraindication screening, eye protection, IFU and a qualified operator’s parameters.','source','https://lumenis.com/aesthetics/products/lightsheer-duet/')
  when p.name ilike 'Toxina Botulínica%' then jsonb_build_object('authority','Anvisa and Ministry of Health safety alert','official_fact','Botulinum-toxin procedures must use registered medicines, authorized services and qualified professionals, following the current bula. Anvisa warns that toxin effects may spread beyond the injection site and that symptoms such as blurred vision, ptosis, slurred speech, difficulty swallowing or breathing require immediate medical attention.','operational_limit','Do not copy dose, dilution, injection points or intervals between products. Record product, manufacturer, lot and current bula.','source','https://www.gov.br/anvisa/pt-br/assuntos/noticias-anvisa/2025/anvisa-e-ministerio-da-saude-alertam-sobre-risco-de-botulismo-iatrogenico-apos-uso-de-toxina-botulinica')
  when p.name ilike '%MMP%' or p.name ilike '%Mesoterapia%' or p.name = 'Enzimas' then jsonb_build_object('authority','Anvisa official aesthetic-product guidance','official_fact','Products applied by injection or microneedling are not cosmetics. Injectable aesthetic products must be regularized as medicines or medical devices and used under qualified supervision according to applicable sanitary regulation and labeling.','operational_limit','Identify the exact product, registration, manufacturer, lot, expiry, route and indication before scheduling or treatment.','source','https://www.gov.br/anvisa/pt-br/assuntos/cosmeticos/cosmeticos-para-tratamentos-esteticos')
  when p.name ilike 'Peeling%' then jsonb_build_object('authority','Anvisa official aesthetic-safety information','official_fact','Anvisa regulates the sanitary aspects of products and services, not a universal “peeling protocol”. Products must be regularized for their intended use; phenol products remain prohibited for aesthetic procedures except exact authorized conditions stated in a medicine/device registration.','operational_limit','Confirm active ingredient, concentration, label, registration, skin assessment, consent and professional protocol. Never use phenol as a cosmetic peel.','source','https://www.gov.br/anvisa/pt-br/comunicacao/campanhas/estetica/fenol')
  else jsonb_build_object('authority','Anvisa official service and device guidance','official_fact','Anvisa states that aesthetic equipment and products must be regularized, that manufacturer instructions define intended use and eligible operators, and that procedure permissions/professional practice are not defined by Anvisa alone.','operational_limit','Confirm local licensing, equipment registration, maintenance, IFU, qualified professional and the clinic’s approved protocol before use.','source','https://www.gov.br/anvisa/pt-br/acessoainformacao/perguntasfrequentes/servicos-de-saude/servicos-de-embelezamento')
end,
catalog_version = greatest(coalesce(p.catalog_version,1),4)
where p.organization_id = 'a783bd4c-f253-4a94-9365-75c6f1000001';

-- Preserve a version snapshot for the bulk official-source update as well as
-- for later edits made through the catalogue UI.
insert into public.procedure_versions(organization_id, procedure_id, version, snapshot, created_by)
select p.organization_id, p.id, p.catalog_version, to_jsonb(p), coalesce(p.created_by, auth.uid())
from public.procedures p
where p.organization_id = 'a783bd4c-f253-4a94-9365-75c6f1000001'
  and p.catalog_version >= 4
on conflict (organization_id, procedure_id, version) do nothing;
commit;
