begin;
alter table public.procedures add column if not exists source_references jsonb not null default '[]' check(jsonb_typeof(source_references)='array');

-- Source-grounded catalogue text. Universal doses, concentrations, laser
-- fluences, needle depths and device settings are intentionally not invented:
-- they belong to the current product label/IFU and approved professional SOP.
update public.procedures p set
description = case p.name
  when 'Enzimas' then 'Procedimento injetável; substância, via, indicação e segurança dependem do produto regularizado identificado no atendimento. Enzimas não designa uma substância única.'
  when 'Jato de Plasma' then 'Aplicação de energia de plasma conforme equipamento, aplicador, indicação autorizada e manual do fabricante.'
  when 'Limpeza de Pele' then 'Higienização, emoliência e extração somente quando indicadas e compatíveis com a barreira cutânea.'
  when 'Peeling de Cristal' then 'Microdermoabrasão superficial com esfoliação mecânica controlada, conforme ponteira e avaliação da pele.'
  when 'Peeling de Diamante' then 'Esfoliação mecânica superficial com ponteira diamantada, selecionada conforme sensibilidade e objetivo.'
  when 'Peeling Ultrassônico' then 'Higienização/esfoliação superficial com espátula ultrassônica conforme manual do equipamento.'
  when 'Peeling Químico' then 'Aplicação tópica de substância química; ativo, concentração, tempo e camadas seguem produto regularizado e protocolo aprovado.'
  when 'PEIM' then 'Procedimento para microvasos selecionados; substância, concentração e técnica dependem da avaliação vascular e do produto regularizado.'
  when 'Radiofrequência' then 'Aquecimento controlado dos tecidos por radiofrequência conforme equipamento, aplicador e indicação autorizada.'
  when 'Ultraformer MPT' then 'Ultrassom focalizado/microfocado conforme modelo, cartucho, indicação autorizada e manual disponível na clínica.'
  when 'Toxina Botulínica — facial' then 'Aplicação de medicamento contendo toxina botulínica em áreas selecionadas, exclusivamente conforme bula e avaliação profissional.'
  when 'Toxina Botulínica — pescoço/mandíbula / técnica Nefertiti' then 'Aplicação cervicofacial selecionada; técnica, pontos e dose não são universais e dependem da anatomia, bula e protocolo.'
  when 'Mesoterapia Capilar / MMP Capilar' then 'Procedimento capilar invasivo; medicamento/produto, via e indicação dependem de avaliação e protocolo específico.'
  when 'MMP — rejuvenescimento / cicatriz de acne / estrias' then 'Microinfusão para objetivo selecionado; produto, profundidade e técnica dependem da indicação e do protocolo profissional.'
  when 'Laser CO₂ AcuPulse — rejuvenescimento profundo' then 'Laser CO₂ para resurfacing/ablação ou vaporização de tecido mole nas indicações previstas para o modelo e aplicador.'
  when 'Laser Harmony — clareamento de manchas' then 'Tecnologia/aplicador Harmony para alterações pigmentares selecionadas após avaliação e diagnóstico diferencial.'
  when 'Laser Harmony — melasma' then 'Abordagem adjuvante para aparência do melasma; não substitui diagnóstico, fotoproteção e manejo contínuo.'
  when 'Laser Harmony — rejuvenescimento leve/moderado' then 'Tratamento não ablativo ou fracionado para textura, tom e fotoenvelhecimento conforme aplicador autorizado.'
  when 'Laser Harmony — remoção de tatuagem/micropigmentação' then 'Clareamento progressivo de pigmento exógeno; resultado depende de cor, profundidade, fototipo e resposta.'
  when 'Laser LightSheer Duet — remoção de pelos / foliculite' then 'Fototermólise seletiva do folículo piloso para redução progressiva de pelos; resposta depende do ciclo, cor e espessura.'
  else 'Procedimento estético individualizado após avaliação profissional.' end,
purpose = case when p.name ilike '%melasma%' then 'Apoiar o controle visual do melasma sem promessa de cura.' when p.name ilike '%pelos%' then 'Reduzir progressivamente pelos e possível pseudofoliculite.' when p.name ilike '%Toxina%' then 'Reduzir temporariamente atividade muscular em áreas selecionadas.' when p.name ilike '%Capilar%' or p.name ilike '%MMP%' then 'Apoiar queixa capilar após investigação e indicação.' else 'Tratar ou melhorar a queixa estética definida na avaliação, sem garantia.' end,
indications = case when p.name ilike '%CO₂%' then 'Rugas, textura e cicatrizes selecionadas dentro da indicação do modelo.' when p.name ilike '%Harmony%manchas%' then 'Alterações pigmentares benignas selecionadas após avaliação.' when p.name ilike '%Harmony%melasma%' then 'Melasma após avaliação, diagnóstico diferencial e plano de fotoproteção.' when p.name ilike '%LightSheer%' then 'Pelos terminais e pseudofoliculite selecionada.' when p.name ilike '%Toxina%' then 'Linhas dinâmicas ou hiperatividade muscular compatíveis com a bula.' when p.name ilike '%Peeling%' then 'Textura, oleosidade ou discromias conforme ativo e profundidade.' when p.name = 'Limpeza de Pele' then 'Comedões e necessidade de higienização quando não houver contraindicação.' else 'Indicação individual confirmada por anamnese e avaliação.' end,
areas = case when p.name ilike '%pescoço%' then 'Pescoço, mandíbula e áreas cervicofaciais avaliadas' when p.name ilike '%Capilar%' or p.name ilike '%MMP%' then 'Couro cabeludo ou face/corpo conforme indicação' when p.name ilike '%pelos%' then 'Áreas com pelos terminais avaliadas' else 'Área definida na avaliação e registrada no atendimento' end,
sessions = 'Não existe número universal; definir por resposta, objetivo, recuperação, intervalo e indicação.',
follow_up = 'Reavaliar conforme recuperação e intervalo do protocolo; antecipar contato diante de sinais de alerta.',
commercial_config = jsonb_build_object('price_status','A definir pela proprietária; não há preço oficial universal.','payment_options','Definir na cobrança.','packages','Não presumir pacote/desconto.','cancellation','Aplicar política da clínica informada antes da reserva.'),
benefits = 'Possível melhora da queixa-alvo dentro dos limites do método, produto/equipamento e resposta individual.',
before_after_care = 'Antes: informar doenças, medicamentos, alergias, gestação/amamentação, infecção, herpes, exposição solar e procedimentos recentes. Depois: seguir orientação escrita, não manipular a área e usar apenas produtos autorizados.',
recovery = 'Pode haver dor, eritema, edema, equimose, ardor, descamação ou sensibilidade; duração depende do procedimento e da resposta individual.',
expected_results = 'Resultados variam; não são garantidos, permanentes ou necessariamente completos. Comparar evolução somente com registro autorizado.',
clinical_details = jsonb_build_object('contraindications','Infecção/lesão ativa, alergia relevante, condição descompensada ou incompatibilidade de bula/manual/protocolo. Avaliar gestação, amamentação, herpes, medicamentos e procedimentos recentes.','risks','Dor, eritema, edema, equimose, irritação, queimadura, pigmentação alterada, infecção, cicatriz, assimetria ou resposta insuficiente.','precautions','Confirmar anamnese, fototipo, área, produto/equipamento regularizado, validade, lote, manutenção, assepsia, consentimento e plano de intercorrência.','urgent_signs','Dor intensa/progressiva, bolhas extensas, necrose, secreção, febre, alteração visual ou dificuldade para falar, engolir ou respirar exigem atendimento imediato.'),
protocol_instructions = 'Executar somente por profissional habilitado, em estabelecimento regularizado, com produto/equipamento regularizado. Conferir bula/rotulagem, IFU, treinamento, manutenção, assepsia, rastreabilidade e consentimento. Registrar avaliação, produto/lote, equipamento/modelo/aplicador, parâmetros realmente usados, intercorrências e retorno.',
materials = jsonb_build_object('products','Somente produtos regularizados, identificados por nome, fabricante, validade e lote; cosméticos não são injetáveis.','equipment','Modelo cadastrado, higienizado e com manutenção em dia.','consumables','EPI, antissepsia, proteção ocular quando indicada e descartáveis compatíveis.'),
documents = jsonb_build_object('consent','Consentimento específico, versão e assinatura quando aplicável.','photos','Fotos técnicas somente com autorização; publicidade exige autorização separada.','signatures','Preservar assinatura, data, versão, profissional e paciente.','traceability','Registrar produto, fabricante, lote, validade, equipamento e parâmetros.'),
availability = jsonb_build_object('status',case when p.active then 'ativo' else 'inativo' end,'professionals','Somente habilitados e autorizados pela proprietária.','booking_visible',p.active,'public_visible',false,'assessment_required',true),
consent_template = 'Consentimento específico: finalidade, alternativas, limitações, riscos, recuperação, cuidados, ausência de garantia, fotos quando aplicável e canais para intercorrências.', consent_template_version = '2026.09-oficial-revisao-profissional',
post_care = 'Seguir orientação individual; manter área limpa, não manipular, evitar sol/calor/atrito e irritantes pelo período indicado e comunicar sinais de alerta.',
relevant_fields = jsonb_build_object('assessment','Indicação, diagnóstico diferencial, fototipo, área, objetivo e expectativas.','safety','Alergias, medicamentos, doenças, gestação/amamentação, infecção e exposição solar.','traceability','Produto, fabricante, lote, validade, equipamento, modelo e parâmetros.'),
device_parameters = jsonb_build_array(jsonb_build_object('name','Parâmetros','value','Preencher somente pelo manual/IFU e pelo protocolo aprovado.'),jsonb_build_object('name','Endpoint','value','Registrar o endpoint definido pelo profissional.'),jsonb_build_object('name','Proteção','value','Registrar proteção ocular/cutânea e medidas aplicadas.')),
source_references = case when p.name ilike 'Toxina Botulínica%' then jsonb_build_array('https://www.gov.br/anvisa/pt-br/assuntos/noticias-anvisa/2025/anvisa-e-ministerio-da-saude-alertam-sobre-risco-de-botulismo-iatrogenico-apos-uso-de-toxina-botulinica','https://www.gov.br/anvisa/pt-br/comunicacao/campanhas/estetica/procedimento-seguro') when p.name ilike 'Laser CO₂%' then jsonb_build_array('https://www.accessdata.fda.gov/cdrh_docs/pdf21/K212703.pdf','https://www.gov.br/anvisa/pt-br/setorregulado/regularizacao/produtos-para-saude/conceitos-e-definicoes/classificacao-de-equipamentos') when p.name ilike 'Laser Harmony%' then jsonb_build_array('https://almalasers.com/product/harmony-xl-pro/','https://www.gov.br/anvisa/pt-br/comunicacao/campanhas/estetica/procedimento-seguro') when p.name ilike 'Laser LightSheer%' then jsonb_build_array('https://lumenis.com/aesthetics/products/lightsheer-duet/','https://www.gov.br/anvisa/pt-br/setorregulado/regularizacao/produtos-para-saude/conceitos-e-definicoes/classificacao-de-equipamentos') when p.name ilike '%MMP%' or p.name ilike '%Mesoterapia%' or p.name = 'Enzimas' then jsonb_build_array('https://www.gov.br/anvisa/pt-br/assuntos/cosmeticos/cosmeticos-para-tratamentos-esteticos','https://www.gov.br/anvisa/pt-br/comunicacao/campanhas/estetica/diferencas-entre-cosmeticos-e-outros-produtos') else jsonb_build_array('https://www.gov.br/anvisa/pt-br/comunicacao/campanhas/estetica/procedimento-seguro','https://www.gov.br/anvisa/pt-br/acessoainformacao/perguntasfrequentes/servicos-de-saude/servicos-de-embelezamento') end,
ai_generated = true, catalog_version = greatest(coalesce(p.catalog_version,1),3)
where p.organization_id = 'a783bd4c-f253-4a94-9365-75c6f1000001';
commit;
